spring:
  application:
    name: WarehouseSystem

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://103.97.126.29:3306/gnnajcqt_warehousesystem
    username: gnnajcqt_warehousesystem
    password: warehouse123

  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangvuvo907@gmail.com
    password: rijw fplk zodm uczx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: hoangvuvo907@gmail.com

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt:
  signerKey: abcDEF123!@#xyz789JWTKeySecret_0123456789012345678901234567890123456789
  valid_duration: 3600
  refresh_token: 30 # days

server:
  address: 0.0.0.0
  port: 8080

frontend:
  domain: http://localhost:5173
